package godo.scene;

public enum Item {

	POTION(0,"Potion"),
	HI_POTION(1,"Hi-Potion"),
	X_POTION(2,"X-Potion"),
	ETHER(3,"Ether"),
	TURBO_ETHER(4,"Turbo Ether"),
	ELIXIR(5,"Elixir"),
	MEGALIXIR(6,"Megalixir"),
	PHOENIX_DOWN(7,"Phoenix Down"),
	ANTIDOTE(8,"Antidote"),
	SOFT(9,"Soft"),
	MAIDENS_KISS(10,"Maiden's Kiss"),
	CORNUCOPIA(11,"Cornucopia"),
	ECHO_SCREEN(12,"Echo Screen"),
	HYPER(13,"Hyper"),
	TRANQUILIZER(14,"Tranquilizer"),
	REMEDY(15,"Remedy"),
	SMOKE_BOMB(16,"Smoke Bomb"),
	SPEED_DRINK(17,"Speed Drink"),
	HERO_DRINK(18,"Hero Drink"),
	VACCINE(19,"Vaccine"),
	GRENADE(20,"Grenade"),
	SHRAPNEL(21,"Shrapnel"),
	RIGHT_ARM(22,"Right arm"),
	HOURGLASS(23,"Hourglass"),
	KISS_OF_DEATH(24,"Kiss of Death"),
	SPIDER_WEB(25,"Spider Web"),
	DREAM_POWDER(26,"Dream Powder"),
	MUTE_MASK(27,"Mute Mask"),
	WAR_GONG(28,"War Gong"),
	LOCO_WEED(29,"Loco weed"),
	FIRE_FANG(30,"Fire Fang"),
	FIRE_VEIL(31,"Fire Veil"),
	ANTARCTIC_WIND(32,"Antarctic Wind"),
	ICE_CRYSTAL(33,"Ice Crystal"),
	BOLT_PLUME(34,"Bolt Plume"),
	SWIFT_BOLT(35,"Swift Bolt"),
	EARTH_DRUM(36,"Earth Drum"),
	EARTH_MALLET(37,"Earth Mallet"),
	DEADLY_WASTE(38,"Deadly Waste"),
	M_TENTACLES(39,"M-Tentacles"),
	STARDUST(40,"Stardust"),
	VAMPIRE_FANG(41,"Vampire Fang"),
	GHOST_HAND(42,"Ghost Hand"),
	VAGYRISK_CLAW(43,"Vagyrisk Claw"),
	LIGHT_CURTAIN(44,"Light Curtain"),
	LUNAR_CURTAIN(45,"Lunar Curtain"),
	MIRROR(46,"Mirror"),
	HOLY_TORCH(47,"Holy Torch"),
	BIRD_WING(48,"Bird Wing"),
	DRAGON_SCALES(49,"Dragon Scales"),
	IMPALER(50,"Impaler"),
	SHRIVEL(51,"Shrivel"),
	EYE_DROP(52,"Eye drop"),
	MOLOTOV(53,"Molotov"),
	S_MINE(54,"S-mine"),
	EIGHT_INCH_CANNON(55,"8inch Cannon"),
	GRAVIBALL(56,"Graviball"),
	TS_BOMB(57,"T/S Bomb"),
	INK(58,"Ink"),
	DAZERS(59,"Dazers"),
	DRAGON_FANG(60,"Dragon Fang"),
	CAULDRON(61,"Cauldron"),
	SYLKIS_GREENS(62,"Sylkis Greens"),
	REAGAN_GREENS(63,"Reagan Greens"),
	MIMETT_GREENS(64,"Mimett Greens"),
	CURIEL_GREENS(65,"Curiel Greens"),
	PAHSANA_GREENS(66,"Pahsana Greens"),
	TANTAL_GREENS(67,"Tantal Greens"),
	KRAKKA_GREENS(68,"Krakka Greens"),
	GYSAHL_GREENS(69,"Gysahl Greens"),
	TENT(70,"Tent"),
	POWER_SOURCE(71,"Power Source"),
	GUARD_SOURCE(72,"Guard Source"),
	MAGIC_SOURCE(73,"Magic Source"),
	MIND_SOURCE(74,"Mind Source"),
	SPEED_SOURCE(75,"Speed Source"),
	LUCK_SOURCE(76,"Luck Source"),
	ZEIO_NUT(77,"Zeio Nut"),
	CAROB_NUT(78,"Carob Nut"),
	POROV_NUT(79,"Porov Nut"),
	PRAM_NUT(80,"Pram Nut"),
	LASAN_NUT(81,"Lasan Nut"),
	SARAHA_NUT(82,"Saraha Nut"),
	LUCHILE_NUT(83,"Luchile Nut"),
	PEPIO_NUT(84,"Pepio Nut"),
	BATTERY(85,"Battery"),
	TISSUE(86,"Tissue"),
	OMNISLASH(87,"Omnislash"),
	CATASTROPHE(88,"Catastrophe"),
	FINAL_HEAVEN(89,"Final Heaven"),
	GREAT_GOSPEL(90,"Great Gospel"),
	COSMO_MEMORY(91,"Cosmo Memory"),
	ALL_CREATION(92,"All Creation"),
	CHAOS(93,"Chaos"),
	HIGHWIND(94,"Highwind"),
	N135_SOLDIER(95,"1/35 soldier"),
	SUPER_SWEEPER(96,"Super Sweeper"),
	MASAMUNE_BLADE(97,"Masamune Blade"),
	SAVE_CRYSTAL(98,"Save Crystal"),
	COMBAT_DIARY(99,"Combat Diary"),
	AUTOGRAPH(100,"Autograph"),
	GAMBLER(101,"Gambler"),
	DESERT_ROSE(102,"Desert Rose"),
	EARTH_HARP(103,"Earth Harp"),
	GUIDE_BOOK(104,"Guide Book"),
	UNKNOWN105(105,""),
	UNKNOWN106(106,""),
	UNKNOWN107(107,""),
	UNKNOWN108(108,""),
	UNKNOWN109(109,""),
	UNKNOWN110(110,""),
	UNKNOWN111(111,""),
	UNKNOWN112(112,""),
	UNKNOWN113(113,""),
	UNKNOWN114(114,""),
	UNKNOWN115(115,""),
	UNKNOWN116(116,""),
	UNKNOWN117(117,""),
	UNKNOWN118(118,""),
	UNKNOWN119(119,""),
	UNKNOWN120(120,""),
	UNKNOWN121(121,""),
	UNKNOWN122(122,""),
	UNKNOWN123(123,""),
	UNKNOWN124(124,""),
	UNKNOWN125(125,""),
	UNKNOWN126(126,""),
	UNKNOWN127(127,""),
	BUSTER_SWORD(128,"Buster Sword"),
	MYTHRIL_SABER(129,"Mythril Saber"),
	HARDEDGE(130,"Hardedge"),
	BUTTERFLY_EDGE(131,"Butterfly Edge"),
	ENHANCE_SWORD(132,"Enhance Sword"),
	ORGANICS(133,"Organics"),
	CRYSTAL_SWORD(134,"Crystal Sword"),
	FORCE_STEALER(135,"Force Stealer"),
	RUNE_BLADE(136,"Rune Blade"),
	MURASAME(137,"Murasame"),
	NAIL_BAT(138,"Nail Bat"),
	YOSHIYUKI(139,"Yoshiyuki"),
	APOCALYPSE(140,"Apocalypse"),
	HEAVENS_CLOUD(141,"Heaven's Cloud"),
	RAGNAROK(142,"Ragnarok"),
	ULTIMA_WEAPON(143,"Ultima Weapon"),
	LEATHER_GLOVE(144,"Leather Glove"),
	METAL_KNUCKLE(145,"Metal Knuckle"),
	MYTHRIL_CLAW(146,"Mythril Claw"),
	GRAND_GLOVE(147,"Grand Glove"),
	TIGER_FANG(148,"Tiger Fang"),
	DIAMOND_KNUCKLE(149,"Diamond Knuckle"),
	DRAGON_CLAW(150,"Dragon Claw"),
	CRYSTAL_GLOVE(151,"Crystal Glove"),
	MOTOR_DRIVE(152,"Motor Drive"),
	PLATINUM_FIST(153,"Platinum Fist"),
	KAISER_KNUCKLE(154,"Kaiser Knuckle"),
	WORK_GLOVE(155,"Work Glove"),
	POWERSOUL(156,"Powersoul"),
	MASTER_FIST(157,"Master Fist"),
	GODS_HAND(158,"God's Hand"),
	PREMIUM_HEART(159,"Premium Heart"),
	GATLING_GUN(160,"Gatling Gun"),
	ASSAULT_GUN(161,"Assault Gun"),
	CANNON_BALL(162,"Cannon Ball"),
	ATOMIC_SCISSORS(163,"Atomic Scissors"),
	HEAVY_VULCAN(164,"Heavy Vulcan"),
	CHAINSAW(165,"Chainsaw"),
	MICROLASER(166,"Microlaser"),
	AM_CANNON(167,"A·M Cannon"),
	W_MACHINE_GUN(168,"W Machine Gun"),
	DRILL_ARM(169,"Drill Arm"),
	SOLID_BAZOOKA(170,"Solid Bazooka"),
	ROCKET_PUNCH(171,"Rocket Punch"),
	ENEMY_LAUNCHER(172,"Enemy Launcher"),
	PILE_BANGER(173,"Pile Banger"),
	MAX_RAY(174,"Max Ray"),
	MISSING_SCORE(175,"Missing Score"),
	MYTHRIL_CLIP(176,"Mythril Clip"),
	DIAMOND_PIN(177,"Diamond Pin"),
	SILVER_BARRETTE(178,"Silver Barrette"),
	GOLD_BARRETTE(179,"Gold Barrette"),
	ADAMAN_CLIP(180,"Adaman Clip"),
	CRYSTAL_COMB(181,"Crystal Comb"),
	MAGIC_COMB(182,"Magic Comb"),
	PLUS_BARRETTE(183,"Plus Barrette"),
	CENTCLIP(184,"Centclip"),
	HAIRPIN(185,"Hairpin"),
	SERAPH_COMB(186,"Seraph Comb"),
	BEHEMOTH_HORN(187,"Behemoth Horn"),
	SPRING_GUN_CLIP(188,"Spring Gun Clip"),
	LIMITED_MOON(189,"Limited Moon"),
	GUARD_STICK(190,"Guard Stick"),
	MYTHRIL_ROD(191,"Mythril Rod"),
	FULL_METAL_STAFF(192,"Full Metal Staff"),
	STRIKING_STAFF(193,"Striking Staff"),
	PRISM_STAFF(194,"Prism Staff"),
	AURORA_ROD(195,"Aurora Rod"),
	WIZARD_STAFF(196,"Wizard Staff"),
	WIZER_STAFF(197,"Wizer Staff"),
	FAIRY_TALE(198,"Fairy Tale"),
	UMBRELLA(199,"Umbrella"),
	PRINCESS_GUARD(200,"Princess Guard"),
	SPEAR(201,"Spear"),
	SLASH_LANCE(202,"Slash Lance"),
	TRIDENT(203,"Trident"),
	MAST_AX(204,"Mast Ax"),
	PARTISAN(205,"Partisan"),
	VIPER_HALBERD(206,"Viper Halberd"),
	JAVELIN(207,"Javelin"),
	GROW_LANCE(208,"Grow Lance"),
	MOP(209,"Mop"),
	DRAGOON_LANCE(210,"Dragoon Lance"),
	SCIMITAR(211,"Scimitar"),
	FLAYER(212,"Flayer"),
	SPIRIT_LANCE(213,"Spirit Lance"),
	VENUS_GOSPEL(214,"Venus Gospel"),
	FOUR_POINT_SHURIKEN(215,"4-point Shuriken"),
	BOOMERANG(216,"Boomerang"),
	PINWHEEL(217,"Pinwheel"),
	RAZOR_RING(218,"Razor Ring"),
	HAWKEYE(219,"Hawkeye"),
	CRYSTAL_CROSS(220,"Crystal Cross"),
	WIND_SLASH(221,"Wind Slash"),
	TWIN_VIPER(222,"Twin Viper"),
	SPIRAL_SHURIKEN(223,"Spiral Shuriken"),
	SUPERBALL(224,"Superball"),
	MAGIC_SHURIKEN(225,"Magic Shuriken"),
	RISING_SUN(226,"Rising Sun"),
	ORITSURU(227,"Oritsuru"),
	CONFORMER(228,"Conformer"),
	YELLOW_MPHONE(229,"Yellow M-phone"),
	GREEN_MPHONE(230,"Green M-phone"),
	BLUE_MPHONE(231,"Blue M-phone"),
	RED_MPHONE(232,"Red M-phone"),
	CRYSTAL_MPHONE(233,"Crystal M-phone"),
	WHITE_MPHONE(234,"White M-phone"),
	BLACK_MPHONE(235,"Black M-phone"),
	SILVER_MPHONE(236,"Silver M-phone"),
	TRUMPET_SHELL(237,"Trumpet Shell"),
	GOLD_MPHONE(238,"Gold M-phone"),
	BATTLE_TRUMPET(239,"Battle Trumpet"),
	STARLIGHT_PHONE(240,"Starlight Phone"),
	HP_SHOUT(241,"HP Shout"),
	QUICKSILVER(242,"Quicksilver"),
	SHOTGUN(243,"Shotgun"),
	SHORTBARREL(244,"Shortbarrel"),
	LARIAT(245,"Lariat"),
	WINCHESTER(246,"Winchester"),
	PEACEMAKER(247,"Peacemaker"),
	BUNTLINE(248,"Buntline"),
	LONG_BARREL_R(249,"Long Barrel R"),
	SILVER_RIFLE(250,"Silver Rifle"),
	SNIPER_CR(251,"Sniper CR"),
	SUPERSHOT_ST(252,"Supershot ST"),
	OUTSIDER(253,"Outsider"),
	DEATH_PENALTY(254,"Death Penalty"),
	MASAMUNE(255,"Masamune"),
	BRONZE_BANGLE(256,"Bronze Bangle"),
	IRON_BANGLE(257,"Iron Bangle"),
	TITAN_BANGLE(258,"Titan Bangle"),
	MYTHRIL_ARMLET(259,"Mythril Armlet"),
	CARBON_BANGLE(260,"Carbon Bangle"),
	SILVER_ARMLET(261,"Silver Armlet"),
	GOLD_ARMLET(262,"Gold Armlet"),
	DIAMOND_BANGLE(263,"Diamond Bangle"),
	CRYSTAL_BANGLE(264,"Crystal Bangle"),
	PLATINUM_BANGLE(265,"Platinum Bangle"),
	RUNE_ARMLET(266,"Rune Armlet"),
	EDINCOAT(267,"Edincoat"),
	WIZARD_BRACELET(268,"Wizard Bracelet"),
	ADAMAN_BANGLE(269,"Adaman Bangle"),
	GIGAS_ARMLET(270,"Gigas Armlet"),
	IMPERIAL_GUARD(271,"Imperial Guard"),
	AEGIS_ARMLET(272,"Aegis Armlet"),
	FOURTH_BRACELET(273,"Fourth Bracelet"),
	WARRIOR_BANGLE(274,"Warrior Bangle"),
	SHINRA_BETA(275,"Shinra Beta"),
	SHINRA_ALPHA(276,"Shinra Alpha"),
	FOUR_SLOTS(277,"Four Slots"),
	FIRE_ARMLET(278,"Fire Armlet"),
	AURORA_ARMLET(279,"Aurora Armlet"),
	BOLT_ARMLET(280,"Bolt Armlet"),
	DRAGON_ARMLET(281,"Dragon Armlet"),
	MINERVA_BAND(282,"Minerva Band"),
	ESCORT_GUARD(283,"Escort Guard"),
	MYSTILE(284,"Mystile"),
	ZIEDRICH(285,"Ziedrich"),
	PRECIOUS_WATCH(286,"Precious Watch"),
	CHOCOBRACELET(287,"Chocobracelet"),
	POWER_WRIST(288,"Power Wrist"),
	PROTECT_VEST(289,"Protect Vest"),
	EARRING(290,"Earring"),
	TALISMAN(291,"Talisman"),
	CHOCO_FEATHER(292,"Choco Feather"),
	AMULET(293,"Amulet"),
	CHAMPION_BELT(294,"Champion Belt"),
	POISON_RING(295,"Poison Ring"),
	TOUPH_RING(296,"Touph Ring"),
	CIRCLET(297,"Circlet"),
	STAR_PENDANT(298,"Star Pendant"),
	SILVER_GLASSES(299,"Silver Glasses"),
	HEADBAND(300,"Headband"),
	FAIRY_RING(301,"Fairy Ring"),
	JEM_RING(302,"Jem Ring"),
	WHITE_CAPE(303,"White Cape"),
	SPRINT_SHOES(304,"Sprint Shoes"),
	PEACE_RING(305,"Peace Ring"),
	RIBBON(306,"Ribbon"),
	FIRE_RING(307,"Fire Ring"),
	ICE_RING(308,"Ice Ring"),
	BOLT_RING(309,"Bolt Ring"),
	TETRA_ELEMENTAL(310,"Tetra Elemental"),
	SAFETY_BIT(311,"Safety Bit"),
	FURY_RING(312,"Fury Ring"),
	CURSE_RING(313,"Curse Ring"),
	PROTECT_RING(314,"Protect Ring"),
	CATS_BELL(315,"Cat's Bell"),
	REFLECT_RING(316,"Reflect Ring"),
	WATER_RING(317,"Water Ring"),
	SNEAK_GLOVE(318,"Sneak Glove"),
	HYPNOCROWN(319,"HypnoCrown"),
	
	NOTHING(0xFFFF,"Nothing");
	
	private int id;
	private String name;

	public int getId() {
		return id;
	}

	public String getName() {
		return name;
	}

	Item(int id, String desc) {
		this.id=id;
		this.name= desc;
		
	}

	public static Item get(int id) {
		for (Item en : Item.values())
			if (en.getId() == id)
				return en;
		return null;
	}

	@Override
	public String toString() {
		return this.getName();
	}
}
